"""empty message

Revision ID: 11940fe34d50
Revises: 
Create Date: 2024-03-18 03:02:09.328661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11940fe34d50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['spotify_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_tracks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
