"""empty message

Revision ID: 1dcdc9c93819
Revises: 5240d85a42be
Create Date: 2024-03-22 17:29:26.040837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dcdc9c93819'
down_revision = '5240d85a42be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_genres', sa.String(length=255), nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('track_genres')

    # ### end Alembic commands ###
