"""empty message

Revision ID: 232ce3ba167d
Revises: 11940fe34d50
Create Date: 2024-03-22 15:29:56.164088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232ce3ba167d'
down_revision = '11940fe34d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
