"""empty message

Revision ID: 27625fc99f9f
Revises: bc7685b9bd89
Create Date: 2024-04-06 03:02:00.305967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '27625fc99f9f'
down_revision = 'bc7685b9bd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('issued_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('expires_in', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('revoked', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('revoked')
        batch_op.drop_column('expires_in')
        batch_op.drop_column('issued_at')
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
