"""empty message

Revision ID: 339f7091f65d
Revises: 7977e460cf38
Create Date: 2024-04-21 02:42:55.203965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '339f7091f65d'
down_revision = '7977e460cf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.alter_column('jti',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.alter_column('jti',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
