"""empty message

Revision ID: 381851843887
Revises: 433c1aab0a94
Create Date: 2024-04-09 16:11:36.688513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381851843887'
down_revision = '433c1aab0a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['host_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###
