"""empty message

Revision ID: 433c1aab0a94
Revises: 977b1f570447
Create Date: 2024-04-09 16:06:18.960469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '433c1aab0a94'
down_revision = '977b1f570447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('room_type', sa.String(length=50), nullable=False))
        batch_op.drop_index('encode_id')
        batch_op.drop_column('encode_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encode_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.create_index('encode_id', ['encode_id'], unique=True)
        batch_op.drop_column('room_type')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
