"""empty message

Revision ID: 47957de76ad9
Revises: 232ce3ba167d
Create Date: 2024-03-22 16:03:19.745264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47957de76ad9'
down_revision = '232ce3ba167d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=255), nullable=True))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
