"""empty message

Revision ID: 5a4fbf1d85ad
Revises: 1dcdc9c93819
Create Date: 2024-03-22 17:45:07.092328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a4fbf1d85ad'
down_revision = '1dcdc9c93819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_genre_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_genre_association',
    sa.Column('track_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], name='track_genre_association_ibfk_2'),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], name='track_genre_association_ibfk_1'),
    sa.PrimaryKeyConstraint('track_id', 'genre_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
