"""empty message

Revision ID: 6e9589931537
Revises: 3bc5452364cf
Create Date: 2024-04-19 03:35:31.008720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e9589931537'
down_revision = '3bc5452364cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(length=100), nullable=True))
        batch_op.drop_column('genre')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encode_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('encode_id')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
