"""empty message

Revision ID: 977b1f570447
Revises: cb66dd7cecf5
Create Date: 2024-04-09 15:49:06.923947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '977b1f570447'
down_revision = 'cb66dd7cecf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
