"""empty message

Revision ID: bc7685b9bd89
Revises: 5a4fbf1d85ad
Create Date: 2024-03-25 23:00:28.812338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7685b9bd89'
down_revision = '5a4fbf1d85ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_track', schema=None) as batch_op:
        batch_op.drop_index('spotify_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_track', schema=None) as batch_op:
        batch_op.create_index('spotify_id', ['spotify_id'], unique=True)

    # ### end Alembic commands ###
